// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2b9XWce-Wq0erVlAPhyZJR1goIdW43RQ',
    appId: '1:1016545780534:web:743f7026e29036c3f7c997',
    messagingSenderId: '1016545780534',
    projectId: 'accordchatapp-49569',
    authDomain: 'accordchatapp-49569.firebaseapp.com',
    storageBucket: 'accordchatapp-49569.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJdCMmRpyBzqUQDshLg6elh6ua3p-lMMA',
    appId: '1:1016545780534:android:1d295713f8f08007f7c997',
    messagingSenderId: '1016545780534',
    projectId: 'accordchatapp-49569',
    storageBucket: 'accordchatapp-49569.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANn71gL6ts907_xSPjLX_WCWnxtHeGCtE',
    appId: '1:1016545780534:ios:9df0294448ba0228f7c997',
    messagingSenderId: '1016545780534',
    projectId: 'accordchatapp-49569',
    storageBucket: 'accordchatapp-49569.appspot.com',
    iosClientId: '1016545780534-heli70vequuu1va33v7ivjaj5qfvpvsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.accord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANn71gL6ts907_xSPjLX_WCWnxtHeGCtE',
    appId: '1:1016545780534:ios:9df0294448ba0228f7c997',
    messagingSenderId: '1016545780534',
    projectId: 'accordchatapp-49569',
    storageBucket: 'accordchatapp-49569.appspot.com',
    iosClientId: '1016545780534-heli70vequuu1va33v7ivjaj5qfvpvsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.accord',
  );
}
